services:
  go-testing:
    image: localhost/go-testing:latest

    build:
      context: .
      dockerfile: Dockerfile

    container_name: go-testing

    restart: unless-stopped

    ports:
      - "4000:4000"

    networks:
      - rizkye-app-network

networks:
  rizkye-app-network:
    external: true