services:
  go-testing:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: go-testing

    restart: unless-stopped

    env_file:
      - .env

    expose:
      - "4000"

    networks:
      - rizkye-app-network

networks:
  rizkye-app-network:
    external: true